### ISSUE TITLE
All feature requests to implement

### ISSUE THREAD

**Issue by PhilPalmer** [TheJacksonLaboratory/splicing-pipelines-nf#55]
## Anne/Laura
- [x] Change `gtf` & `star_index` defaults to ones in Sumner in Olga's lab directory #50

## Pablo
- [x] Add rmats postprocessing #16 

## Phil
- [x] Big changes
    - [x] Allow multiple rmats executions (combine the b1 & b2 into a single input file) #53
    - [x] Run each rMATS process twice, once for each GTF file #54
    - [x] Add get count matrix #49
- [x] Trimming #52 
    - [x] Add trimmomatic logs to output dir
    - [x] Add FastQC after trimming
    - [x] Add trimmed FASTQC results to MultiQC (see [here](https://github.com/ewels/MultiQC/issues/620))
- [x] Change readlength params #47 
    - [x] Change the `overhang` default to `false` 
    - [x] Remove default read length value
    - [x] Cause the pipeline to fail if read length is not set
- [x] Add adapter sequences for trimmomatic #48
- [ ] Outputs #52
    - [x] Change big wig output file name
    - [ ] Cleanup output directory
- [x] Docs #51 
    - [x] Add instructions to get help message to [`README.md`](https://github.com/TheJacksonLaboratory/splicing-pipelines-nf/blob/master/README.md)
     - [x] Add Nextflow advanced options to docs eg `-with-dag` from [here](https://www.nextflow.io/docs/latest/tracing.html?highlight=dag) to documentation
    - [x] Add more info for parameters
    - [x] Author edit #56
    - [x] Update dag
