### ISSUE TITLE
Modify pipeline to run with TCGA & GTEX data

### ISSUE THREAD

**Issue by PhilPalmer** [TheJacksonLaboratory/splicing-pipelines-nf#84]
- [x] Add [get_accession](https://github.com/lifebit-ai/rmats-nf/blob/master/main.nf#L93-L117) process to download data from TCGA/GTEX
- [x] Extract FASTQ from BAMs using [bamtofastq](https://bedtools.readthedocs.io/en/latest/content/tools/bamtofastq.html) (TCGA only)
- [ ] Add further postprocessing to merge rMATS outputs into a single matrix (by junction positions)
- [ ] Optimise pipeline to run more efficiently / cheaper on cloud
    - [ ] Make pipeline public to import on CloudOS?
    - [ ] Benchmark (samples will be run binned by length & run in batches eg 48/50bp + 75/76bp?)
    - [ ] Update resources
- [ ] Transdecoder ORF -> peptides?

Ideally, the pipeline would accept either FASTQ/BAM input directly provided by the user for from TCGA/GTEX

## EDIT: additional requirements (11/06/2020)
- [x] Containers
    - [x] add new rmats container
    - [x] XS tag (awk script) fix #120 
- [x] For trimmomatic: 
    - [x] add option to remove quality filtering in trimmomatic
        - [x] add option to remove ~crop/~ minlength for trimmomatic (default read length - int)
        - [x] add option to slidingwindow (bool)
- [x] For [rMATS](https://github.com/Xinglab/rmats-turbo/blob/v4.1.0/README.md):
    - [x] paired_stats (bool - default = false)
    - [x] add option to turn stat_off (bool)
    - [x] add option to use variable read length for TCGA (bool)
    - [x] add option for novel splice site selection for new rmats (bool)
        - [x] min intron & min exon (check rmats defaults & set in `nextflow.config`, int)
- [ ] If possible and not too complicated: 
    - [x] option to use only b1 for rmats instead of having b1 and b2
    - [ ] turn off the merged gtf step (and subsequent rmats step)?

### To Do
- [x] 1) #125 Add (`samtools view -H`) check for single vs paired BAMs & save info
- [x] 2) #132 (Laura:) Add prefix to counts matrix and multiQC so they won't all have the same name
- [x] 3) #124 (Laura:) When TCGA is run, run STAR with modified parameters 
- [x] 4) #138 (Phil:) fix paired-end incorrect processing (GTEx only)
- [ ] 5) #139 Upload STAR indexes to GCloud
- [ ] 6) #140 Optimise pipeline to run more effectively in the Cloud

### Done
- [x] 1) Added processes to download & extract reads from TCGA/GTEx/SRA
- [x] 2) Add BAM input support (see Brittany's diagram below, & #131)
- [x] 3) Bug fix for stranded data
- [x] 4) Updated rMATS version
- [x] 5) Added new parameters for trimmomatic and rMATS
- [x] 6) Fix memory issue (add `max_memory` support, see #119)
- [x] 7) Check `b1` input only (Nice to have - see above)

![image](https://user-images.githubusercontent.com/32334279/85041986-8bf25200-b182-11ea-9b4b-ca95999e99fe.png)

**Comment by Vlad-Dembrovskyi** [comment]
Done. Closing.
